GET http://localhost:8088/preparedExercises
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjdkNmUwN2Q1LTc5MTktNDE4NS04MDE2LTdmMWIwMDE3MTczOSIsIm5hbWUiOiJsaW51c0B0b3J3YWxkcy5wbCIsImVtYWlsIjoibGludXNAdG9yd2FsZHMucGwiLCJqdGkiOiJlNmUwOTZmYS1kYjViLTRiZDgtOGNkNy1hMmY0MWI2YmVjNDgiLCJpYXQiOjE2ODU3MzYzNTYsIm5iZiI6MTY4NTczNjM1NiwiZXhwIjoxNjg1NzM5OTU2fQ.k5NOVb3_m9ZHqIEEomzxTEezuaGk-wDs_-Tn70fE69U