GET http://192.168.1.107:8088/sections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFhZTFkMjY2LTE5ZjYtNGE3NS1iYmJkLThhNTQwOTFmMWY2MyIsIm5hbWUiOiJyaWNoYXJkNkBzdGFsbG1hbi5wbCIsImVtYWlsIjoicmljaGFyZDZAc3RhbGxtYW4ucGwiLCJqdGkiOiJiZTdmMmNmNS1jMDJlLTRlOWQtYTM0Ny00YjBkYjM5OWE1NzkiLCJpYXQiOjE2ODYwODYyMDksIm5iZiI6MTY4NjA4NjIwOSwiZXhwIjoxNjg2MDg2MjY5fQ.Ta-SwKkLYDTCyWg5OHHmmsmDxXzbUc0G3vlbEJ8HOo4