POST http://localhost:5202/exercises
Content-Type: application/json

{
    "sectionId": 1,
    "image": "bench_press.jpg",
    "name": "Bench press",
    "description": [
        "40 kg",
        "12 reps",
        "3 sets"
    ]
}