@id = 0a224d60-0f93-40a9-929f-64bfea9a5627
PUT http://localhost:5202/exercises/{{id}}
Content-Type: application/json

{
    "sectionId": 2,
    "image": "pull_up.jpg",
    "name": "Pull ups",
    "description": [
        "12 reps",
        "3 sets"
    ]
}