@id = 1a243f81-15f8-47fe-8dfc-ca5da1cfb7f8

DELETE http://192.168.1.107:8088/exercises/single/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNWRmNTkyLTM0ZGQtNDg5Mi1iZGRiLTAzNmY3YTYxMzdiMSIsIm5hbWUiOiJqYW5Aa293YWxza2kucGwiLCJlbWFpbCI6ImphbkBrb3dhbHNraS5wbCIsImp0aSI6IjNkMDYxZGUyLTJiZTUtNDIyYS1hMjkwLTM4ODJkM2UwN2M2ZSIsImlhdCI6MTY4NTcyMTkzOSwibmJmIjoxNjg1NzIxOTM5LCJleHAiOjE2ODU3MjU1Mzl9.miUNctFnFeY43meAEXRj-nS7ArfF_cygGykoPivx9bg