@id = 29e92b3d-7cb9-41df-a39f-d9ad4cd3411c
PUT http://localhost:8088/exercises/{{id}}
Content-Type: application/json

{
    "sectionId": "1397f67f-0fed-4234-8af0-2a0454fb4651",
    "userId": "329c8676-446e-4c4f-93fc-16dd91773782",
    "name": "Incline dumbell bench press"
}