@id = 71f7d5cf-2ffd-46d1-b9d1-a027834b7d8d

DELETE http://localhost:8088/exercises/{{id}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEwNWRmNTkyLTM0ZGQtNDg5Mi1iZGRiLTAzNmY3YTYxMzdiMSIsIm5hbWUiOiJqYW5Aa293YWxza2kucGwiLCJlbWFpbCI6ImphbkBrb3dhbHNraS5wbCIsImp0aSI6IjNkMDYxZGUyLTJiZTUtNDIyYS1hMjkwLTM4ODJkM2UwN2M2ZSIsImlhdCI6MTY4NTcyMTkzOSwibmJmIjoxNjg1NzIxOTM5LCJleHAiOjE2ODU3MjU1Mzl9.miUNctFnFeY43meAEXRj-nS7ArfF_cygGykoPivx9bg