POST http://localhost:8088/auth/RefreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4ZTFkNzYwLWQwODYtNDVhZS1iMDdlLTgyMjE1NmM2ZGJmZSIsIm5hbWUiOiJyaWNoYXJkMkBzdGFsbG1hbi5wbCIsImVtYWlsIjoicmljaGFyZDJAc3RhbGxtYW4ucGwiLCJqdGkiOiI3YjViZGM2NS00ZTFjLTQxMzEtOWExNy00MGZiODAzMzM2YjYiLCJpYXQiOjE2ODYyNTcyMTYsIm5iZiI6MTY4NjI1NzIxNiwiZXhwIjoxNjg2MjU3Mjc2fQ.8oIiKwwMPkztC4Ajw4byC6yObiK9D6T_vOC343gDIeM",
  "refreshToken": "albgyUtfXiV20F3JkjMZw9b"
}