POST http://localhost:8088/auth/RefreshToken
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI4ZTFkNzYwLWQwODYtNDVhZS1iMDdlLTgyMjE1NmM2ZGJmZSIsIm5hbWUiOiJyaWNoYXJkMkBzdGFsbG1hbi5wbCIsImVtYWlsIjoicmljaGFyZDJAc3RhbGxtYW4ucGwiLCJqdGkiOiIzZjhlNjlkMy0wNjlmLTQxOWEtOTM1OS0zMDQ0OGVlNTk0ZWMiLCJpYXQiOjE2ODYwODY0NDIsIm5iZiI6MTY4NjA4NjQ0MiwiZXhwIjoxNjg2MDg2NTAyfQ.LMoipe9u18zfQDRdODNUYPxS9u5S_aKq3YMmIZWKcq0",
  "refreshToken": "TiloofehukONSbD1znwudoy"
}